<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            [
                'name'=>'view-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'show-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'create-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'edit-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'delete-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'under-review-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'on-hold-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'approve-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'reject-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'cancel-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'generate-pdf-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'generate-excel-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'export-data-talent-applications',
                'guard_name'=>'web',
                'type'=>'talent-applications',
            ],
            [
                'name'=>'view-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'show-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'create-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'edit-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'delete-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'under-review-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'on-hold-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'approve-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'reject-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'cancel-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'generate-pdf-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'generate-excel-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'export-data-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'entrepreneur-applications',
            ],
            [
                'name'=>'view-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'show-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'create-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'edit-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'delete-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'under-review-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'on-hold-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'approve-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'reject-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'cancel-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'generate-pdf-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'generate-excel-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'export-data-investor-applications',
                'guard_name'=>'web',
                'type'=>'investor-applications',
            ],
            [
                'name'=>'view-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'show-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'create-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'edit-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'delete-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'under-review-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'on-hold-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'approve-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'reject-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'cancel-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'generate-pdf-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'generate-excel-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'export-data-executive-applications',
                'guard_name'=>'web',
                'type'=>'executive-applications',
            ],
            [
                'name'=>'view-categories',
                'guard_name'=>'web',
                'type'=>'categories',
            ],
            [
                'name'=>'show-categories',
                'guard_name'=>'web',
                'type'=>'categories',
            ],
            [
                'name'=>'create-categories',
                'guard_name'=>'web',
                'type'=>'categories',
            ],
            [
                'name'=>'edit-categories',
                'guard_name'=>'web',
                'type'=>'categories',
            ],
            [
                'name'=>'delete-categories',
                'guard_name'=>'web',
                'type'=>'categories',
            ],
            [
                'name'=>'view-sub-categories',
                'guard_name'=>'web',
                'type'=>'sub-categories',
            ],
            [
                'name'=>'show-sub-categories',
                'guard_name'=>'web',
                'type'=>'sub-categories',
            ],
            [
                'name'=>'create-sub-categories',
                'guard_name'=>'web',
                'type'=>'sub-categories',
            ],
            [
                'name'=>'edit-sub-categories',
                'guard_name'=>'web',
                'type'=>'sub-categories',
            ],
            [
                'name'=>'delete-sub-categories',
                'guard_name'=>'web',
                'type'=>'sub-categories',
            ],
            [
                'name'=>'view-sectors',
                'guard_name'=>'web',
                'type'=>'sectors',
            ],
            [
                'name'=>'show-sectors',
                'guard_name'=>'web',
                'type'=>'sectors',
            ],
            [
                'name'=>'create-sectors',
                'guard_name'=>'web',
                'type'=>'sectors',
            ],
            [
                'name'=>'edit-sectors',
                'guard_name'=>'web',
                'type'=>'sectors',
            ],
            [
                'name'=>'delete-sectors',
                'guard_name'=>'web',
                'type'=>'sectors',
            ],
            [
                'name'=>'view-activities',
                'guard_name'=>'web',
                'type'=>'activities',
            ],
            [
                'name'=>'show-activities',
                'guard_name'=>'web',
                'type'=>'activities',
            ],
            [
                'name'=>'create-activities',
                'guard_name'=>'web',
                'type'=>'activities',
            ],
            [
                'name'=>'edit-activities',
                'guard_name'=>'web',
                'type'=>'activities',
            ],
            [
                'name'=>'delete-activities',
                'guard_name'=>'web',
                'type'=>'activities',
            ],
            [
                'name'=>'view-sub-activities',
                'guard_name'=>'web',
                'type'=>'sub-activities',
            ],
            [
                'name'=>'show-sub-activities',
                'guard_name'=>'web',
                'type'=>'sub-activities',
            ],
            [
                'name'=>'create-sub-activities',
                'guard_name'=>'web',
                'type'=>'sub-activities',
            ],
            [
                'name'=>'edit-sub-activities',
                'guard_name'=>'web',
                'type'=>'sub-activities',
            ],
            [
                'name'=>'delete-sub-activities',
                'guard_name'=>'web',
                'type'=>'sub-activities',
            ],
            [
                'name'=>'view-entities',
                'guard_name'=>'web',
                'type'=>'entities',
            ],
            [
                'name'=>'show-entities',
                'guard_name'=>'web',
                'type'=>'entities',
            ],
            [
                'name'=>'create-entities',
                'guard_name'=>'web',
                'type'=>'entities',
            ],
            [
                'name'=>'edit-entities',
                'guard_name'=>'web',
                'type'=>'entities',
            ],
            [
                'name'=>'delete-entities',
                'guard_name'=>'web',
                'type'=>'entities',
            ],
            [
                'name'=>'view-incubators',
                'guard_name'=>'web',
                'type'=>'incubators',
            ],
            [
                'name'=>'show-incubators',
                'guard_name'=>'web',
                'type'=>'incubators',
            ],
            [
                'name'=>'create-incubators',
                'guard_name'=>'web',
                'type'=>'incubators',
            ],
            [
                'name'=>'edit-incubators',
                'guard_name'=>'web',
                'type'=>'incubators',
            ],
            [
                'name'=>'delete-incubators',
                'guard_name'=>'web',
                'type'=>'incubators',
            ],
            [
                'name'=>'view-form-fields',
                'guard_name'=>'web',
                'type'=>'form-fields',
            ],
            [
                'name'=>'show-form-fields',
                'guard_name'=>'web',
                'type'=>'form-fields',
            ],
            [
                'name'=>'create-form-fields',
                'guard_name'=>'web',
                'type'=>'form-fields',
            ],
            [
                'name'=>'edit-form-fields',
                'guard_name'=>'web',
                'type'=>'form-fields',
            ],
            [
                'name'=>'delete-form-fields',
                'guard_name'=>'web',
                'type'=>'form-fields',
            ],
            [
                'name'=>'view-stages',
                'guard_name'=>'web',
                'type'=>'stages',
            ],
            [
                'name'=>'show-stages',
                'guard_name'=>'web',
                'type'=>'stages',
            ],
            [
                'name'=>'create-stages',
                'guard_name'=>'web',
                'type'=>'stages',
            ],
            [
                'name'=>'edit-stages',
                'guard_name'=>'web',
                'type'=>'stages',
            ],
            [
                'name'=>'delete-stages',
                'guard_name'=>'web',
                'type'=>'stages',
            ],
            [
                'name'=>'view-stage-statuses',
                'guard_name'=>'web',
                'type'=>'stage-statuses',
            ],
            [
                'name'=>'show-stage-statuses',
                'guard_name'=>'web',
                'type'=>'stage-statuses',
            ],
            [
                'name'=>'create-stage-statuses',
                'guard_name'=>'web',
                'type'=>'stage-statuses',
            ],
            [
                'name'=>'edit-stage-statuses',
                'guard_name'=>'web',
                'type'=>'stage-statuses',
            ],
            [
                'name'=>'delete-stage-statuses',
                'guard_name'=>'web',
                'type'=>'stage-statuses',
            ],
            [
                'name'=>'view-applicant-users',
                'guard_name'=>'web',
                'type'=>'applicant-users',
            ],
            [
                'name'=>'show-applicant-users',
                'guard_name'=>'web',
                'type'=>'applicant-users',
            ],
            [
                'name'=>'create-applicant-users',
                'guard_name'=>'web',
                'type'=>'applicant-users',
            ],
            [
                'name'=>'edit-applicant-users',
                'guard_name'=>'web',
                'type'=>'applicant-users',
            ],
            [
                'name'=>'delete-applicant-users',
                'guard_name'=>'web',
                'type'=>'applicant-users',
            ],
            [
                'name'=>'view-admin-users',
                'guard_name'=>'web',
                'type'=>'admin-users',
            ],
            [
                'name'=>'show-admin-users',
                'guard_name'=>'web',
                'type'=>'admin-users',
            ],
            [
                'name'=>'create-admin-users',
                'guard_name'=>'web',
                'type'=>'admin-users',
            ],
            [
                'name'=>'edit-admin-users',
                'guard_name'=>'web',
                'type'=>'admin-users',
            ],
            [
                'name'=>'delete-admin-users',
                'guard_name'=>'web',
                'type'=>'admin-users',
            ],
            [
                'name'=>'view-entity-users',
                'guard_name'=>'web',
                'type'=>'entity-users',
            ],
            [
                'name'=>'show-entity-users',
                'guard_name'=>'web',
                'type'=>'entity-users',
            ],
            [
                'name'=>'create-entity-users',
                'guard_name'=>'web',
                'type'=>'entity-users',
            ],
            [
                'name'=>'edit-entity-users',
                'guard_name'=>'web',
                'type'=>'entity-users',
            ],
            [
                'name'=>'delete-entity-users',
                'guard_name'=>'web',
                'type'=>'entity-users',
            ],
            [
                'name'=>'view-roles',
                'guard_name'=>'web',
                'type'=>'roles',
            ],
            [
                'name'=>'show-roles',
                'guard_name'=>'web',
                'type'=>'roles',
            ],
            [
                'name'=>'create-roles',
                'guard_name'=>'web',
                'type'=>'roles',
            ],
            [
                'name'=>'edit-roles',
                'guard_name'=>'web',
                'type'=>'roles',
            ],
            [
                'name'=>'delete-roles',
                'guard_name'=>'web',
                'type'=>'roles',
            ],
            [
                'name'=>'view-promotional-emails',
                'guard_name'=>'web',
                'type'=>'promotional-emails',
            ],
            [
                'name'=>'delete-promotional-emails',
                'guard_name'=>'web',
                'type'=>'promotional-emails',
            ],
            [
                'name'=>'view-quality-checks',
                'guard_name'=>'web',
                'type'=>'quality-checks',
            ],
            [
                'name'=>'show-quality-checks',
                'guard_name'=>'web',
                'type'=>'quality-checks',
            ],
            [
                'name'=>'request-quality-checks',
                'guard_name'=>'web',
                'type'=>'quality-checks',
            ],
            [
                'name'=>'approve-quality-checks',
                'guard_name'=>'web',
                'type'=>'quality-checks',
            ],
            [
                'name'=>'reject-quality-checks',
                'guard_name'=>'web',
                'type'=>'quality-checks',
            ],
            [
                'name'=>'view-audit-talent-applications',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-entrepreneur-applications',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-investor-applications',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-executive-applications',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-categories',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-sub-categories',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-sectors',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-activities',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-sub-activities',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-entities',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-incubators',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-form-fields',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-stages',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-stage-statuses',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-applicant-users',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-admin-users',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-entity-users',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-roles',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-audit-promotional-emails',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-deleted-audit',
                'guard_name'=>'web',
                'type'=>'audit',
            ],
            [
                'name'=>'view-talent-application-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-entrepreneur-application-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-investor-application-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-executive-application-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-talent-category-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-entrepreneur-category-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-investor-category-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-executive-category-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-talent-entities-performance-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-entrepreneur-entities-performance-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-investor-entities-performance-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-executive-entities-performance-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-monthly-statistacs',
                'guard_name'=>'web',
                'type'=>'dashboard',
            ],
            [
                'name'=>'view-application-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-jusour-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-entity-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-moci-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-vfs-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-mol-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
            [
                'name'=>'view-hayya-statuses',
                'guard_name'=>'web',
                'type'=>'statuses',
            ],
        ];

        foreach ($permissions as $permission) {
            $per = Permission::where(['name'=>$permission['name'],'guard_name'=>'web','type'=>$permission['type']])->first();
            if(empty($per)){
                Permission::create($permission);
            }
        }
    }
}
